#! /bin/sh

#
# make sure all processes are killed
#

killall -q polybar
killall -q sxhkd
killall -q picom
killall -q bato

#
# something
#

pgrep -x sxhkd > /dev/null
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
while pgrep -u $UID -x bato >/dev/null; do sleep 1; done
# while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

#
# AUTOSTART
#

xsetroot -cursor_name arrow
sxhkd & # keymap
bato & # batery notification
nitrogen --restore & 
pulseaudio -k -D & # audio
dunst -config $HOME/.config/dunst/dunstrc & # dunstify configuration
bash ~/.config/polybar/launch.sh & # polybar
signal-desktop --start-in-tray --use-tray-icon --no-sandbox %U &
xrdb ~/.Xresources &
wmname LG3D &
picom --experimental-backends &

# Translation
if [ "$(xsel)" == "" ]; then
  dunstify "Translation" "clipboard is blank and have nothing to do"
fi

#
# bspwm
# 

bspc monitor -d 一 二 三 四 五 六 

bspc config border_width        1
bspc config window_gap          5

bspc config normal_border_color  "#090909" # #02020E" #"#222d70" #C93357
bspc config focused_border_color "#090909"     #"#f288a2"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 
# 2's workspace used for internet browser.
bspc rule -a google-chrome-stable desktop='^2' state=floating follow=on

# 4's workspace used for online chating binaries.
bspc rule -a Discrod desktop='^4' state=floating follow=on
bspc rule -a telegram-desktop desktop='^4' state=floating follow=on
