#! /bin/sh

#
# make sure all processes are killed
#

killall -q polybar
killall -q sxhkd
killall -q picom
killall -q bato

#
# something
#

pgrep -x sxhkd > /dev/null
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
while pgrep -u $UID -x bato >/dev/null; do sleep 1; done
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

#
# AUTOSTART
#

sxhkd & # keymap
bato & # batery notification
nitrogen --restore & # wallpaper
picom --experimental-backend & # compositor
pulseaudio -k -D & # audio
dunst -config $HOME/.config/dunst/dunstrc & # dunstify configuration
$HOME/.config/polybar_baru/launch.sh & # polybar
signal-desktop --start-in-tray --use-tray-icon --no-sandbox %U &
xrdb ~/.Xresources &

#
# bspwm
# 

bspc monitor -d 1 2 3 4 5  

bspc config border_width        2
bspc config window_gap          5

bspc config normal_border_color "#222d70" #C93357
bspc config focused_border_color "#5463c4"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 
# 2's workspace used for internet browser.
bspc rule -f google-chrome-stable desktop='^2'  

# 4's workspace used for online chating binaries.
bspc rule -f discrod desktop='^4'
bspc rule -a telegram-desktop desktop='^4'
